<a href="https://colab.research.google.com/github/Kushagragoel-code/data-science/blob/main/day-6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
dct = {
    'name':['tom','nick','krish','jack'],
    'age':[20,21,19,18],
    'roll':[1,2,3,4]
}
df = pd.DataFrame(dct)
display(df)

df.info()

    name  age  roll
0    tom   20     1
1   nick   21     2
2  krish   19     3
3   jack   18     4

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   age     4 non-null      int64
 2   roll    4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [ ]:
df = pd.read_csv('/content/student_data.csv')
display(df)

df.info()

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   study_hours            10000 non-null  int64
 1   attendance             10000 non-null  int64
 2   sleep_hours            10000 non-null  int64
 3   internet_usage         10000 non-null  int64
 4   assignments_completed  10000 non-null  int64
 5   previous_score         10000 non-null  int64
 6   exam_score             10000 non-null  float64
 7   placement_status       10000 non-null  object
dtypes: float64(1), int64(6), object(1)
memory usage: 625.1+ KB

In [ ]:

df = pd.read_csv('/content/student_data.csv')
df.describe()

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score
count,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000
mean,5.989600,69.88460,6.498500,6.062600,9.988400,64.91100,86.704207
std,3.163589,17.61653,1.709354,3.138163,6.034145,17.50302,15.058383
min,1.000000,40.00000,4.000000,1.000000,0.000000,35.00000,26.670000
25%,3.000000,55.00000,5.000000,3.000000,5.000000,50.00000,76.727500
50%,6.000000,70.00000,6.500000,6.000000,10.000000,65.00000,92.120000
75%,9.000000,85.00000,8.000000,9.000000,15.000000,80.00000,100.000000
max,11.000000,100.00000,9.000000,11.000000,20.000000,95.00000,100.000000

In [ ]:
df = pd.read_csv('/content/student_data.csv')
# df.tail(5)
# df[['study_hours','internet_usage']]
# df.study_hours
df.iloc[0:5]
df.loc[df['study_hours']==11]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
2,11,60,7,6,10,45,100.00,Placed
9,11,77,4,9,15,69,100.00,Placed
10,11,64,8,8,12,76,100.00,Placed
29,11,63,9,10,1,72,96.59,Placed
30,11,45,5,2,4,93,100.00,Placed
...,...,...,...,...,...,...,...,...
9969,11,84,8,2,3,83,100.00,Placed
9971,11,81,9,6,0,85,100.00,Placed
9978,11,92,8,2,16,79,100.00,Placed
9979,11,78,9,5,18,82,100.00,Placed
9988,11,94,6,9,6,67,100.00,Placed

In [ ]:
df=pd.read_csv('/content/student_data.csv')
# df.loc[df['study_hours']==11,['study_hours','sleep_hours']].iloc[4:8]
df2 = df.loc[df['study_hours']==11]
df2[['study_hours','sleep_hours']]
df.loc[4]

study_hours                   5
attendance                   52
sleep_hours                   8
internet_usage                6
assignments_completed         8
previous_score               40
exam_score                78.82
placement_status         Placed
Name: 4, dtype: object

In [ ]:
df = pd.read_csv('/content/student_data.csv')
# df.loc[df['assignments_completed']==8,['assignments_completed']].iloc[0:]
# df.loc[df['assignments_completed']>3]
# df.rename(columns = {'assignments_completed':'assign_com'} ,inplace = True)
# display(df)

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
4,5,52,8,6,8,40,78.82,Placed
5,7,40,9,10,0,60,72.33,Placed
...,...,...,...,...,...,...,...,...
9994,4,53,7,8,10,71,85.02,Placed
9995,2,58,9,7,8,88,69.31,Not Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [ ]:
import pandas as pd
import numpy as np # Import numpy

dct ={
    'name':['tom','nick','krish','jack'],
    'age':[20,np.nan,19,18],
    'roll':[1,2,3,4],
    'marks':[90,80,70,60]
}
df = pd.DataFrame(dct)
df.isna()
df.notnull()
df.fillna(0)

    name   age  roll  marks
0    tom  20.0     1     90
1   nick   0.0     2     80
2  krish  19.0     3     70
3   jack  18.0     4     60

In [ ]:
df['attendence'].unique()

KeyError: 'attendence'